// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./ui/styles/globals.css";
import SideNav from "./ui/components/sidenav";
import styles from "./ui/styles/layout.module.css";
import { ClientSessionProvider } from "./ui/components/ClientSessionProvider";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientSessionProvider>
          <div className={styles.layout}>
            <div className={styles.sideNav}>
              <SideNav />
            </div>
            <main className={styles.mainContent}>{children}</main>
          </div>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
